projectType = "gradle-project"
language = "java"
platformVersion = ""
packaging = "jar"
configurationFileFormat = "properties"
javaVersion = 17
groupId = "org.turntabl"
artifactId = "hopper"
name = "hopper"
description = "Demo hopper game built in Spring boot"
packageName = "org.turntabl.hopper"
dependencies = "security"
bootVersion = "4.0.2"
version = "0.0.1-SNAPSHOT"
